language: node_js
sudo: false
node_js:
- 8
script:
- npm run lint
- npm test
- npm run test:browser
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: FsWJf8L8CkEco6syoDWg3mVZTlHqF+lhNHIfEX4+cvbmaQt2dMEJv7V1TCKWLaNJol1eC1ghHhci/gam57gnmTc0SyKU3zymu5zmpYXg6bkjowHuaFwFkepcGMGSoLYI83Hs6Moz8xa2aO/gARUTJYSTxD3LQNl9bibjHDRbwk3Nw8sG3MZEikyL7Q3Cjvuk2V98x2jyf+s1ChvkAS8KI7EzQav3+sBN/EAS6W8du5bM4JNGTAYE/gocgWETpzKeFb6NIuwiOcvHL8/HYiQ4XYppcQeNspgyZ3lqLYQc3FBCiUMc4bMTFst918xoxSBmWlndNBl//dzBg1q4IXli5Q0o3q8RRXwYhk8YtmFBFJKhznzbh7J2hHBRmEGBwCPbJ+7A6jNGcu/CyY89+bAw4SjfQWmk8z9FCfLF/nD4Cn8Xed1GZIMsWBLpyQaslmwSDltsiE+JEDIA2u1VfTCMbBsTEJx3bSX5QysN8eDIQL1A8NoXn1pjLUrKP8Ez+vYeWA8dxZdJBc552qXushE41rj/w+31Mgvm5kzDY2ShL0gSMCxqdaGaWhIF6AyO8MW9yTv6b9tn+3eWgnEawQDswx5viQpJpPVKsNAxZIpko1Qs0VwvhKPuyqiXJEwC00t1lOuuQo1FD6vmRqJn1gpD29bAO+uBmTbT8nD/IrS73Io=
env:
  global:
    secure: XTcADlw/Z15Cjt0Ct7jUFafFffZnHGdGgchJTheCG3hnp2IsQpCk8xPayaJB/i8yaonWCmKfEmppscKBiNcjf5bUGYgtIZWe5bYVSgj55FVMPjG6ytVTPQMqJdZx87thjHpUBU6IQxkWw9tObPTdiYxiDzrOLgeTsaiJCZba/iVE4g0Nkxoz8mm6buWNMfNybKbGE+z6bc1wpfjPm9AYxNIv+e7GLDcEVAA7SZ4zDWbVgPsr+KGK2mSUrxc0+JjxK+H4Nfq5Lyd095x0Hzs1vyaEuvpdUGR5AocJIU/yHG8gH/Dau5oA+YKVGBH+PbpKQLvNoGYSKxkPPyt4qWlQ5zYWbdM69WUqCui/jcHINFsoTCNVEiRkAbmBGeHwcJQkAr8MH1/v4TYed/kJeMr10INeatAeWPQTfHKzjT1blmt/TvOdDZt2g6gGay9zKQ4NgXo2LELMl8iqjAObRXSXW1ba2SI+nmw7VntG/LOsHcZ8S9dUshCIDWt0rrYt8cbZJkWlVKxN8TiuCEvG+hCINmkyLZRX2E2pWRtJtT79sACrfQhiNr1pcA9xBEx9sOxnBTZ3k9qEES0AfIY28cEsHlcIeDY4RGdTPHDTG+9YcYRpbf7Up3iDLD4g9x0OuWH8NJrmPv3qoGb7fN5PKFwnu1LyE6iBoyZPi31jBqvgZyY=
