language: node_js
sudo: false
node_js:
- 8
script:
- npm run lint
- npm test
- npm run test:browser
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: FsWJf8L8CkEco6syoDWg3mVZTlHqF+lhNHIfEX4+cvbmaQt2dMEJv7V1TCKWLaNJol1eC1ghHhci/gam57gnmTc0SyKU3zymu5zmpYXg6bkjowHuaFwFkepcGMGSoLYI83Hs6Moz8xa2aO/gARUTJYSTxD3LQNl9bibjHDRbwk3Nw8sG3MZEikyL7Q3Cjvuk2V98x2jyf+s1ChvkAS8KI7EzQav3+sBN/EAS6W8du5bM4JNGTAYE/gocgWETpzKeFb6NIuwiOcvHL8/HYiQ4XYppcQeNspgyZ3lqLYQc3FBCiUMc4bMTFst918xoxSBmWlndNBl//dzBg1q4IXli5Q0o3q8RRXwYhk8YtmFBFJKhznzbh7J2hHBRmEGBwCPbJ+7A6jNGcu/CyY89+bAw4SjfQWmk8z9FCfLF/nD4Cn8Xed1GZIMsWBLpyQaslmwSDltsiE+JEDIA2u1VfTCMbBsTEJx3bSX5QysN8eDIQL1A8NoXn1pjLUrKP8Ez+vYeWA8dxZdJBc552qXushE41rj/w+31Mgvm5kzDY2ShL0gSMCxqdaGaWhIF6AyO8MW9yTv6b9tn+3eWgnEawQDswx5viQpJpPVKsNAxZIpko1Qs0VwvhKPuyqiXJEwC00t1lOuuQo1FD6vmRqJn1gpD29bAO+uBmTbT8nD/IrS73Io=
env:
  global:
  - secure: YceR/aEBk3AvFegOhFTZoVkE/Lgq9KBF+PynQgeg02zuvV26LGLzd0/hSlZAoWN2V5WtkqkH0tuapWQANXTsJrvmt1ZdHwwDVrJsS00Rr9iFxdmOaAT69cnnwskbVyo8GwuwUWyXCcOXl4iXCNeS12GGeA2ghKujqj6f+3rVZ3ah6/kSsFfEXHM2n3UGy4M/HsB1dRV3TeSVPdG34nYMox7yOfEIvjIzAS7r/AUbG/LU3hwJuJq4jM3svhbNXRPH8pFP8nxg3zQlQ+Aid5tNq3sqt+E+1F/ZTI3C/PhQiqzf1Wv0L9EOYCRsA6DmJ0vmuVXOftHWrIPEPebKaEDvK+h8cxLxhuRkSrE8xLi/mur2nuGgV6jPSbisV88WuKYdWBCqEn98AKZb+jXSbOFNdonSFBQRL4DuZTq0fR0QgvqyW/dtZcuImgsc8MGJ9XgurVQq4WwyKDs7KH+cqbyj+M3xDSjMRANulEYSuNyY4v6l7xiQv2Kvz7pvHIpZQ+RWPJG6D3z/tmVpMx0m5N/EJtep8m05h18WB18mqm61UrNoDjFUl4bw2gnXMlGCG7y/aSn60x+RyIe9zANWt/XvgI2HvGO+4kp8TfNwHQg2NnVvQtvtmCL54HrIX+Hy3pD7wi3WvhJ/g+4QXESLUjV+/DFf/kC+bL26pVBy7OItUoE=
