language: node_js
sudo: false
node_js:
- 8
script:
- npm run lint
- npm test
- npm run test:browser
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: R/mi5E01mjnf4EtPWasCyTHjm30Yf0ZNokA0n6slI/u4NSHCjnU8fhFGq7LBrEDYuGOirmQnCD5H/18Gd3nyVYJSH/nrdLYVkTXSmUSSRBR93E2jYoqeHQpH8HOAZmkLyZg8w5jNB7re8GVlPWOE/Se1pxmp0+iUZfSHHdrUk3yGrYQ7VdQffYnfj3ZyCaOn/rorIjzgoHoR1Nr9UsqeXe9+6YrUpb3LwX00wZpgoOxeKGCQIL3Tov8ejfWp23iiGZVdOQ+Kbmz8P4O28nVceepzhqZn5+4fo8gGKwZmo1OfgpWWV8wXxjgs7kN2pXNFZTp0h6nmcqVVzaLwwKCG6IGrCQ23c47NhW/NSB6epTUjhlGxHyCgUa2MiittBUbmOFvc89xwcLRbPhMzgteGusZP/rTNivYgZW98YTJcEJuxpMsW8xwjFv8VRMfwY6FreJ7EF+a5CMrTORt8fD3i6jNDcyGKxYZ/+lGI9gFcmbojCqAECdGXqHO26YOKkb6ytUH01gsgWhrbXDktsvRZzRA0DTX4KD3TZEfhWZOWpBQccn1bzuVPmsXCx6hxWyvFNF3ZyQmrVqgWx1MQsIF01K7Rlo08nVcQKG3K/CrD3S8pNlnzcNHdBkuJaZnTQ4NRdJqola7adp6OFzo2xI1sGXFmhEuTxtTSOTPvsgBwJnA=
env:
  global:
  - secure: YceR/aEBk3AvFegOhFTZoVkE/Lgq9KBF+PynQgeg02zuvV26LGLzd0/hSlZAoWN2V5WtkqkH0tuapWQANXTsJrvmt1ZdHwwDVrJsS00Rr9iFxdmOaAT69cnnwskbVyo8GwuwUWyXCcOXl4iXCNeS12GGeA2ghKujqj6f+3rVZ3ah6/kSsFfEXHM2n3UGy4M/HsB1dRV3TeSVPdG34nYMox7yOfEIvjIzAS7r/AUbG/LU3hwJuJq4jM3svhbNXRPH8pFP8nxg3zQlQ+Aid5tNq3sqt+E+1F/ZTI3C/PhQiqzf1Wv0L9EOYCRsA6DmJ0vmuVXOftHWrIPEPebKaEDvK+h8cxLxhuRkSrE8xLi/mur2nuGgV6jPSbisV88WuKYdWBCqEn98AKZb+jXSbOFNdonSFBQRL4DuZTq0fR0QgvqyW/dtZcuImgsc8MGJ9XgurVQq4WwyKDs7KH+cqbyj+M3xDSjMRANulEYSuNyY4v6l7xiQv2Kvz7pvHIpZQ+RWPJG6D3z/tmVpMx0m5N/EJtep8m05h18WB18mqm61UrNoDjFUl4bw2gnXMlGCG7y/aSn60x+RyIe9zANWt/XvgI2HvGO+4kp8TfNwHQg2NnVvQtvtmCL54HrIX+Hy3pD7wi3WvhJ/g+4QXESLUjV+/DFf/kC+bL26pVBy7OItUoE=
