language: node_js
sudo: false
node_js:
- 8
install:
- npm install
- npm install codecov
script:
- npm run lint
- npm test
- npm run test:browser
- codecov
before_deploy:
- snyk monitor --org=serverless
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: T2djPdGcnoT6ZTAfCPsP2qFEVhgMhJ/OGBSxQsP+P8bKhSSfEzLKccurBM34Ul0V4D9tdDsoYnGVpo6LSqv38u1WJ4jrUk75hn308/hjQxIhtSIvzd8Z5Hqx6OTL0u1FshBoBx/0e2YNdzChPa+lT9pFFJPLErGuL/WzjZNlSruJXs1dXSipuqvSLhf4oA67maYMkMkNlr8eSliaJvETQm7CwiVUTsEI4aK3nTUdQFKcTdN+YD3dL1IkTTUacoQ5NA51TM46xYjlVu0sINV748ONmvRs9Yalp1H90e14h44ZjhEiShLn3WKahRTJ2Yx+HsyZG26cGz9mona3SqaIkEbTRlatdWP610r8DUwd0Wx1YnINZDwOXQcEjQdL7md5//xPSRdvJPtTFn63xC3gJoYPnvnKHWT4L+xwL1GznRptWIOJ953bt0YvacR+ZvOO9uDHH0S3EtCq0qUqjcSehDIgh6vEmy3tZ8NQaa+mTlDxm6kYWOGOVZnakVBmEajNGSmo9yOaCMeoGvizWhKY6fbwW7FepkW9plHkTgENIB3yZQITz1Sj0apzpSm/oRrEWbhizkgoGGjV3SL1e7SPPVFqzX2jIrS6siLB1jPr5mKX1ALPfpUTlKrRG2BUZgQMZHT0d6XxvG2dpiDk2Ff524RYlAj4sk5DNgLLJGtQpFQ=
env:
  global:
  - secure: YceR/aEBk3AvFegOhFTZoVkE/Lgq9KBF+PynQgeg02zuvV26LGLzd0/hSlZAoWN2V5WtkqkH0tuapWQANXTsJrvmt1ZdHwwDVrJsS00Rr9iFxdmOaAT69cnnwskbVyo8GwuwUWyXCcOXl4iXCNeS12GGeA2ghKujqj6f+3rVZ3ah6/kSsFfEXHM2n3UGy4M/HsB1dRV3TeSVPdG34nYMox7yOfEIvjIzAS7r/AUbG/LU3hwJuJq4jM3svhbNXRPH8pFP8nxg3zQlQ+Aid5tNq3sqt+E+1F/ZTI3C/PhQiqzf1Wv0L9EOYCRsA6DmJ0vmuVXOftHWrIPEPebKaEDvK+h8cxLxhuRkSrE8xLi/mur2nuGgV6jPSbisV88WuKYdWBCqEn98AKZb+jXSbOFNdonSFBQRL4DuZTq0fR0QgvqyW/dtZcuImgsc8MGJ9XgurVQq4WwyKDs7KH+cqbyj+M3xDSjMRANulEYSuNyY4v6l7xiQv2Kvz7pvHIpZQ+RWPJG6D3z/tmVpMx0m5N/EJtep8m05h18WB18mqm61UrNoDjFUl4bw2gnXMlGCG7y/aSn60x+RyIe9zANWt/XvgI2HvGO+4kp8TfNwHQg2NnVvQtvtmCL54HrIX+Hy3pD7wi3WvhJ/g+4QXESLUjV+/DFf/kC+bL26pVBy7OItUoE=
  - secure: NQaU5xImX2ONDZ06LUWMVdPDIsyGH0Nt4G2qKRehnsc3+XM9ae0Vc0vihAc0aZ9L1w5VmiCg0TInqxNyGjo0m5kwu0Hrh0KkCL3KZxDKfLdcrCaGI5FYCSGrhzmi42TNRR5hxxvf13An+rFVcT47DaRAJZHTW+gGU0jATHkJC8nCOOWvySuWDDynP7FNh/I6zi12wgQF/yQU0AeJr7WK+XL2+f3cuCbe79ZaC8g77VbRhA/WsoTicKAThShekOB7W5+OG8OUHDiytA+Yz1QHCa8Ez4gzPHAPSLePAsqZIVIZMarhZyDY5bM6EedO7eHPtjEVpBQB2T+8sAXONGczKbwftjW4xc+n0DHN8Rm3W4f/bq0+AIGI5EWAOb57CrQg2t91nXQf8/XoQQwboyAsj6nSuWAIMohzmOWDaB7SCobMohqsyuC6BGg1COt7sGMqCwHiFINGklfhcXmn2aeoJXdP9MjX7MaUSwK6/5hJRwFQv0AjrMh30a1BL3xPvqDI/JV8PiGEDZJos9u31ey3vkHmKab5lhSDV1X7+VEpaas6TLoislPmb68VdNf1vvhme9PtfUGHyuVU3ooGqaRQr5BdztHnexGDANT9zGeiCWlZHL6lU0DQ4KwZN6dROe6Guc+gILMy6O2pk1TaSKD9NUmSyK+RsONNvPMeB0i1yy8=
